### ISSUE TITLE
Catalog modals are broken when using dist

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#1900]
![screen shot 2017-08-01 at 3 18 32 pm](https://user-images.githubusercontent.com/895728/28843264-86951500-76ce-11e7-8796-2bece8833cf0.PNG)

Known issues:

* button labels are showing angular expressions
* the modals don't actually work

**Comment by spadgett** [comment]
@jeff-phillips-18 @dtaylor113 FYI, the dialogs are broken, but only in the minified JS. You should be able to see this with

```
$ grunt serve:dist
```

in origin-web-console

**Comment by dtaylor113** [comment]
I'm seeing this error in the console:

```
vendor.js:5659 Error: [$injector:unpr] Unknown provider: tProvider <- t
http://errors.angularjs.org/1.5.11/$injector/unpr?p0=tProvider%20%3C-%20t
    at vendor.js:3372
    at vendor.js:4147
    at Object.i [as get] (vendor.js:4085)
    at vendor.js:4149
    at i (vendor.js:4085)
    at r (vendor.js:4096)
    at Object.invoke (vendor.js:4106)
    at c.instance (vendor.js:5086)
    at f (vendor.js:4624)
    at vendor.js:4530
```
Think it has something to do with this: https://stackoverflow.com/questions/27343739/what-does-error-injectorunpr-unknown-provider-tprovider-t-myactiveli
"If you're minifying your code, don't use the inference style of dependency annotation. Use the $inject property or use inline annotation"  Hmm...but we do use `$inject`

**Comment by jeff-phillips-18** [comment]
I simply added angular-patternfly.js to index.html and it fixed it 😕

**Comment by spadgett** [comment]
angular-patternfly has `mangle: false`, probably for this reason.

https://github.com/patternfly/angular-patternfly/blob/master/Gruntfile.js#L310

ng-annotate needs an `"ngInject";` prologue to work with Angular 1.5 components, which angular-patternfly doesn't us. So even updating ng-annotate (#1889) won't fix the problem.

https://github.com/olov/ng-annotate#ng-annotate-

ng-annotate is also deprecated.

We either need to

1. disable mangling,
2. disable minification of our dependencies, or
3. add the `"ngInject";` prologue (or array notation for dependencies) to angular-patternfly.

But (3) won't help if we run into this with another dependency.

@jeff-phillips-18 @dtaylor113 any strong opinions?

**Comment by spadgett** [comment]
Looks like disabling mangling on vendor.js increases size from 3.2 MB -> 4.0 MB, which is not insignificant.

**Comment by jeff-phillips-18** [comment]
Can we do 2 but use the min version of the dependencies if they exist?

**Comment by spadgett** [comment]
Yeah was just looking at that.

Having trouble setting different uglify options with usemin :/

**Comment by spadgett** [comment]
It looks like package maintainers generally provide the un-minified version as their bower main. The bower spec specifically says not to include minified files:

https://github.com/bower/spec/blob/master/json.md#main

Then downstream projects typically concat and minify (like we do). This poses two potential problems:

1. To use the minified versions directly, we'll need to list of the minified js files for each package, which might become a pain to maintain.
2. Other downstream projects using angular-patternfly are likely to run into this problem with minification.

Even if we go with one of the other options, I'm a little worried about (2).

**Comment by jeff-phillips-18** [comment]
This is an issue in angular patternfly with the https://github.com/patternfly/angular-patternfly/blob/master/src/wizard/wizard-buttons.js file. I have a fix in hand that I am finishing testing on.

**Comment by jeff-phillips-18** [comment]
Opened issue https://github.com/patternfly/angular-patternfly/issues/544

**Comment by jeff-phillips-18** [comment]
Not closed until we upgrade to the next Angular Patternfly release
